### ISSUE TITLE
🐹 hamster-html: the injection-safe html function

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#107]
we need a tagged-template function that allows us to generate safe html.

please see the pattern we are currently using in [example-app's index.html.ts](https://github.com/chase-moskal/example-app/blob/16e9e61ffa696f907b7098558d9b2dc83d9af479/s/web/templates/index.html.ts)

the above approach has the following problem:

- **it's not injection-safe**  
    there is a severe danger of xss injection vulnerability with the current approach.

    let's imagine we have the following code:

    ```js
    html`<div>${user.profile.nickname}</div>`
    ```

    this is fine if the user's nickname is `Johnny` — but if the user maliciously chooses a nickname like `<script>console.error('hacked')</script>`, they could hijack the entire application, impersonating users, compromising the entire app, perhaps even phishing for credit card numbers.

    we need to create a safe `html` function that will, by default, escape the html.

when this work is completed:

- **we will create a new toolbox function**  
    `s/toolbox/hamster-html/html.ts` that exports a new `html` tagged-template function.

- **the new html function must html-escape values by default**

    we can use the existing [escape-html.ts](https://github.com/chase-moskal/xiome/blob/c01c06531ba9d5d609805e9ce0408d1b34da2089/s/toolbox/escape-html.ts) to make a string injection safe.

    the usage of the new function will keep us safe from xss injection attacks:

    ```js
    html`<div>${"<script>console.error('hacked')</script>"}</div>`
    ```
    
    it will render the following safe html:

    ```html
    <div>&lt;script&gt;console.error('hacked')&lt;/script&gt;</div>
    ```

    this needs to be the default rendering for values inserted into the html function via the `${}` syntax.

- **however, devs still need a way to inject html!**

    the real question, is that we need to figure out how developers should consciously inject dangerous html, and making it very obvious so that they don't accidentally render a dangerous value as a html.

    there are probably many ways this could be done, i'm not sure which is best. here's some ideas:

    ```js
    // sanitized/escaped by default
    html`<div>${"<p>hello</p>")}</div>`
      // &lt;p&gt;hello&lt;/p&gt;

    // nested html functions must NOT sanitized
    html`<div>${html`<p>hello</p>`}</div>`
      // <div><p>hello</p></div>
    ```

so, here are the requirements for this work:
- [x] new `html` function in `s/toolbox/hamster-html/html.ts`
- [x] by default, sanitize values to make them xss-safe by using `escape-html.ts`
- [x] allow developers an explicit way to deliberately inject html (by nesting `html` calls)
- [x] write a cynic test suite that proves it works `s/toolbox/hamster-html/html.test.ts`

------

:moneybag: bitcoin bounty starts at `50k satoshis`
:money_with_wings: bounty falls in value each day by `5k satoshis` after `2020-01-10`

**Comment by PaulAroo** [comment]
I would like to be assigned this ticket
