### ISSUE TITLE
👥 chat viewer and participant counts

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#117]
we want the chat to display the current count of people who are viewing the chat, and also how many are participating in the chat

it would be nice to also have svg icons representing each count

- serverside stat counting is now implemented on chatp4 08a6d54dd597a40c7e29cc424c4ac8ad7f461ca0
- now we need the `chatModel` to request the stats from the serverside
- the chat model needs to insert the stats into the chat state
- then the chat component needs to render the stats from the state, into a new footer below the rest of the chat component

---

:moneybag: bitcoin bounty `50k satoshis`
:money_with_wings: bounty falls by `10k satoshis` each day after 2022-01-11

**Comment by PaulAroo** [comment]
I would like to be assigned this ticket

**Comment by chase-moskal** [comment]
![Screenshot 2022-01-17 074700](https://user-images.githubusercontent.com/7145590/149800669-fac8e44f-7429-4065-9677-cef6e48ea4ad.png)

**Comment by chase-moskal** [comment]
:tada: merged to master, good work @PaulAroo
