### ISSUE TITLE
create a new xio-price-input component and xio-price-display

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#146]
![Image](https://user-images.githubusercontent.com/7145590/177208759-0f0b330c-860c-45d1-958b-f84b4768c441.png)

the above input sucks and doesn't work for prices (it's just a `xio-text-input`)

we need a decent design that
- includes a dollar sign (configurable for different currencies?)
- includes the three-letter iso currency code (like "USD", or "CAD", "NGN" -- should configurable)
- limit decimal precision to cents (two digits after decimal? configurable?)
- investigates built-in inputs (number inputs? are these useful at all, or just a pain to work with?)
- work well on phones and desktop alike
- validation for impossible prices (can't be negative, can't be zero)
- should it display large numbers with commas and such?
- should numbers after the decimal (cents) be displayed in a smaller font size?
- should it have little up and down arrows, for incrementing/decrementing dollars and cents?
- should dollar input and cents input be one input, or two side-by-side?
- should probably have a text label similar to `<xio-text-input>my cool label</xio-text-input>`
- simple to use as html component
    ```html
    <xio-price-input
      currency="USD"
      symbol="$"
      initial-value="9.99"
      min="1.00"
      max="100000"
    ></xio-price-input>
    ```

we need a matching price-display component
- if the input component is for inputting a price -- the display component will display such a price
- price display component should have very similar configurable attributes as price input component
- the two are like sister components that pair well together
- should display the currency symbol (like "$") and the currency three-letter code (like "USD")
- i think it would look nice if cents were displayed in a smaller font (configurable, `cents-superscript`)

further things to consider
- not all currencies have "cents" (maybe there's a more generic term we should use?)

**Comment by PaulAroo** [comment]
- [ ]  add chevrons (little up and down arrows), preferably from feather icons
- [ ] implement configurable superscript for `xio-price-display`
