### ISSUE TITLE
investigate/experiment with loading spinners inside modals for upgrades/downgrades/cancel/renew etc

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#179]
currently, doing something like an upgrade has a user experience like this:
1. click upgrade button
2. confirmation modal appears (click yes)
3. modal disappears and we probably see a loading spinner where the upgrade button used to be
4. an alert modal appears reminding us that it's completed

it would be a superior user experience if we achieved something more like this:
1. click upgrade button
2. confirmation modal appears (click yes)
3. the loading indicator (spinner) actually renders INSIDE the modal (the modal remains up until the loading is completed)
4. when the loading for the upgrade action is completed, the modal simply disappears

something like that.

there's just something awkward about the modal appearing, then disappearing, then reappearing.

***note***

the goal of this ticket is not necessarily to actually implement this feature (though that would be good) -- we actually just want to explore and understand how difficult this would be to implement -- and if it turns out to be moderately tricky to accompish, we very well may skip it for now

**Comment by chase-moskal** [comment]
it probably would involve making a custom modal (using something like `modals.popup`, i think?) that might be built in a similar pattern as the other modals like `confirm` and `alert` and `prompt` -- although this new modal would contain this special ability to show a loading spinner 🤷‍♂

**Comment by PaulAroo** [comment]
- we want an `ok` button` when an error occurs while we are in the modal
- we should make popup html structure more like confirm, so the modal styles work
