### ISSUE TITLE
implement xiome-notes-indicator component

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#72]
this is an icon, with a bell-icon, and a red indicator, for how many new notes are in your inbox

- [x] add a nice notifications bell icon svg, if we don't already have one
- [x] red indicator bubble indicates number of new notes (color is customizable by custom css property `--xiome-notes-indicator-color`)
- [x] flexible size, customizable via `width` and `height` on the `:host` (but defaults to 3em)
- [x] find a way to integrate the red notifications bubble onto the `<xiome-my-avatar>` for when notes component might be placed alongside the account panel (instead of being a separate panel)
  - this means notes might have a standalone bell icon to open the notes panel,
  - or optionally the notes panel might live alongside the account panel, in which case the red indicator should appear on top of the avatar icon
  - integration with my-avatar should not couple my-avatar to the notes-indicator -- perhaps the notes indicator should be capable to be drawn on top of my-avatar or any other square icon for that matter

---

:moneybag: bitcoin bounty starts at `30k satoshis`
:money_with_wings: bounty falls in value by `2k` each day after 2021-10-23

**Comment by zenkyuv** [comment]
1Hkt5Nw2ZRiukUS3GRobgaE2dLh8RZ97kL

**Comment by chase-moskal** [comment]
transaction sent https://www.blockchain.com/btc/address/1Hkt5Nw2ZRiukUS3GRobgaE2dLh8RZ97kL
