### ISSUE TITLE
select loses selection in video display controls when triangle is toggled

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#80]
to reproduce the bug:
1. http://localhost:5000/x/mocksite/videos
2. login as `creative@xiome.io`
3. open a video display controls
4. make some selections in the select boxes
5. toggle the triangle closed and then open again
6. observe that the selection has been lost (although if you click assign, it remembers the last selection)

to fix:
- we need to find a way to preserve the selection when open/close happens

---

:moneybag: bitcoin bounty `10k satoshis`
:money_with_wings: this bounty falls in value by `2k` each day after 2021-10-30

**Comment by zenkyuv** [comment]
you can assign me, im almost done with it, i though at first im not gonna make it so i didnt want to be assigned but after being clarified maybe i will make this i just need to fix some another bugs which appeared

**Comment by chase-moskal** [comment]
merged. bounty has fallen to zero.
