### ISSUE TITLE
notes-model and xiome-notes functionality stub

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#84]
start with the stub for `createNotesCache` in the latest `chase/notes` branch

@chase-moskal should make these preparations
- [x] write tests that exercise the caching mechanism
- [x] complete full system integration into mocksite and real xiome
  - broadcasting system
  - some mechanism to populate with testing notes

for the assignee
- [x] provide a mechanism that each xiome-notes-component will use to interact with the notes model, such that data is cached so it can be rendered (our goal is to keep caching logic out of the component and in the model, to keep components as simple as possible)
- [x] wire the cache state up to the notes-component so the component rerenders when the cache state changes
- [x] clear the cache and refresh note pages when a broadcast event comes from a change in another browser tab
- [x] write xiome-notes component stub
  - write the component code that interacts with the notes-model and cache
  - this is preparation for the component work ticket https://github.com/chase-moskal/xiome/issues/73
  - match functionality of this design https://github.com/chase-moskal/xiome/issues/62#issuecomment-947987934
  - component functionally works on the mocksite without errors
  - [x] show messages like "you have no new notifications" and "you have no old notifications" when notes list is empty
  - [x] make sure there are no pagination bugs
    - make sure pagination seems to be working
    - check for bugs involving pagination going out-of-range by marking many notes
    - check for pagination falling out of sync
  - [x] add a way for the frontend to style the `new` or `old` buttons to highlight the active tab
  - [x] don't render the pagination when there's nothing to do (next/previous are not available)
  - [x] render all of the details about each note
  - in the developer console on the mocksite, you can use `fakeNote()` to generate a fake note, for testing purposes
    - you can use `localStorage.clear()` to wipe all mock data and start fresh again
    - after each of these actions, you'll need to refresh the browser
---

:moneybag: bitcoin bounty `100k satoshis`
:money_with_wings: bounty falls in value by `10k satoshis` per day after 2021-11-04

**Comment by PaulAroo** [comment]
I would like to be assigned this task

**Comment by chase-moskal** [comment]
this is done and merged to master

i calculate the reward `20k satoshis`

@PaulAroo please post a public bitcoin wallet address where i can send the reward :beers:

**Comment by PaulAroo** [comment]
> `1Bb6xH14kx96mh8j5P7RPSWsi3jxKvkHvD`

**Comment by chase-moskal** [comment]
@PaulAroo sent

https://btc5.trezor.io/tx/cab1a07745425379f7cf6fb70669dcb5a8f3e62db694eee2f7d8af019af5fe0e
