### ISSUE TITLE
chat component basic layout and styles

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#86]
the chat is ready for styling :sunglasses: 

see the component on `master`'s mocksite chat page http://localhost:5000/x/mocksite/chat

the component is functionally implemented, but need to look pretty

- [x] write css to style the component to match the design sketch (see in comment below)
  - style the moderation header
  - style the participation area (with the text input and send button)
- [x] do NOT style anything under the `.history` class — that's for another ticket
- [x] use some cool svg icons for some of the buttons
- [x] make the thing customizable via css custom properties and some css parts

---

:moneybag: bitcoin bounty `50k satoshis`
:money_with_wings: falls in value `5k satoshis` each day after 2021-11-14

**Comment by chase-moskal** [comment]
![Screenshot 2021-11-13 184822](https://user-images.githubusercontent.com/7145590/141665547-22b7003f-dacf-495d-8c53-5893f3edc4ea.png)

**Comment by gelatinadenaranja** [comment]
Well since no one else did this yet guess i'll do it

**Comment by chase-moskal** [comment]
@gelatinadenaranja assigned 👍 👍

**Comment by gelatinadenaranja** [comment]
Should all buttons on the moderation header be right aligned or only the chat on/off one?

**Comment by chase-moskal** [comment]
@gelatinadenaranja i think we should put the chat room label on the left, and the chat on/off toggle on the right

**Comment by gelatinadenaranja** [comment]
Hello i'm back from x-mas with a hole in my liver for eating so much crap. Anyways, the on/off toggle button now floats to the right. How would you like the participation area?

**Comment by chase-moskal** [comment]
@gelatinadenaranja i too am recovering from the overfeeding ;)

as for the participation area, it's hard to say much more than "like the design sketch" until i have a draft to compare against -- i suppose i'll say "use your best judgement" and we'll go from there :beers:
