### ISSUE TITLE
chat history styles and user experience

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#87]
chat mocksite http://localhost:5000/x/mocksite/chat

- [ ] style the chat history area in accordance to design sketch (see in comment below)
  - don't worry about the rest of the component's styles, that's handled by #86
- [x] make it so that the chat history area is independently scrollable
- [x] make the chat history keep scrolled to the bottom,
  - unless the user starts scrolling and breaks away from the bottom
- [x] use svg icons for moderation controls like mute and delete
- [x] only display the first 5 characters of the user ids, make it small, subtle, low-opacity
- [x] messages should be compact, so many can fit

---

:moneybag: bitcoin bounty `50k satoshis`
:money_with_wings: falls in value by `5k satoshis` each day after 2021-11-14

**Comment by chase-moskal** [comment]
![Screenshot 2021-11-13 184822](https://user-images.githubusercontent.com/7145590/141665559-634b921e-5c63-46ec-bd5a-0c3d31e30a38.png)

**Comment by gelatinadenaranja** [comment]
May i try to take this task on? I think it'll take me at least ~5-6 days maybe since this is my first task and i'll have to learn typescript and lit-html
