### ISSUE TITLE
chat validation

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#88]
chat mocksite http://localhost:5000/x/mocksite/chat

implement serverside and clientside validation for the chat feature

base your work on `chatvalidation` branch, to inherit the test suite

- [x] validate all inputs coming into the functions returned by `chat-serverside-logic.ts` (but don't worry about `meta`, which is validated by the `policy`)
- [x] write darkvalley validators (in the new `chat-validators.ts`)
- [x] validate user inputs on the frontend (the message textbox)
- [x] satisfy all the new chat validation tests

---

:moneybag: bitcoin bounty `30k satoshis`
:money_with_wings: falls in value by `2.5k satoshis` each day after 2021-11-14

**Comment by chase-moskal** [comment]
readme has docs on how darkvalley works

https://github.com/chase-moskal/xiome#darkvalley--minimalistic-validation

**Comment by zenkyuv** [comment]
can you assign me to this ?

**Comment by chase-moskal** [comment]
reworked the ticket to reflect the new test suite in `chatvalidation` branch

**Comment by chase-moskal** [comment]
@zenkyuv i've added a new commit onto my version of the `chatvalidation` branch

please review it

now, all that's left for you to complete this work, is the add the chat validator to the frontend clientside, by attaching the `validateChatContent` to the `xio-text-input` in the web component

**Comment by chase-moskal** [comment]
@zenkyuv this work is now done and merged, excellent.

the bitcoin bounty had expired.
