### ISSUE TITLE
chat web socket implementation

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#89]
the serverside is already done. probably.

- [ ] write the clientside websocket plumbing in `api/sockets/chat-socket-client.ts`
  - use the `chat-client-core.ts` similarly to how `chat-mock-client.ts`
  - but using websocket client to implement `connectToServer` instead of the servelet
  - return the chatConnect function from the clientside core you've wired with websocket
- [ ] run the chat server in node
- [ ] hack `assemble-models.ts` so that it connects to the locally running chat node server
  - make the chat mocksite work against the node server http://localhost:5000/x/mocksite/chat
- [ ] make sure a code reviewer knows how to run the chat server and test this thing on the mocksite

---

:moneybag: bitcoin bounty `60k satoshis`
:money_with_wings: falls in value by `3k` each day after 2021-11-14

**Comment by chase-moskal** [comment]
![Screenshot 2021-11-13 184934](https://user-images.githubusercontent.com/7145590/141665606-cc941155-4feb-4da6-8ad6-d614ce65dcdf.png)

**Comment by zenkyuv** [comment]
You can assign me to this

**Comment by chase-moskal** [comment]
- get the server running on 8000
- write `chat-socket-client.ts`
  - use builtin browser websocket https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications
- in `assemble-mocks.ts`, replace `chatMockClient` with the new `chatSocketClient`
- manually test the chat feature on the mocksite http://localhost:5000/x/mocksite/chat

**Comment by chase-moskal** [comment]
closing in favor of #101
