### ISSUE TITLE
chat persistence layer

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#90]
- [ ] implement a real replacement for `mock-chat-persistence.ts`
- [ ] decide and what kind of realtime database this will connect to
  - mongodb?
  - redis? rethink? something else?
  - maybe even a custom node microservice?
- [ ] hack it in to replace mock-chat-persistence, test it locally

---

:moneybag: bitcoin bounty `60k satoshis`
:money_with_wings: falls in value by `3k satoshis` each day after 2021-11-14

**Comment by chase-moskal** [comment]
![Screenshot 2021-11-13 184934](https://user-images.githubusercontent.com/7145590/141665610-f988dcb1-2a6b-4db1-bb09-13351adaa4d9.png)

**Comment by PaulAroo** [comment]
I would like to be assigned this task

**Comment by chase-moskal** [comment]
we've run into complications on this issue

mongodb isn't capable of returning the details of a deleted item, which poses a problem as our implementation relied on mongodb to propagate all changes across to the chat servers.

we'll need to go back to the drawing board on this issue.

since the chat system currently works, using the mock chat persistence layer, we are going to shelf this issue until it become a higher priority (when we need to run multiple replicas of the chat server)
