### ISSUE TITLE
notes component layout and styling

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#91]
see the notes mocksite http://localhost:5000/x/mocksite/notes

in the javascript console, call `fakeNote()` whenever you want to spawn a note for the current user -- then you have to refresh the browser, because we don't have realtime updates for this

- [ ] make the xiome-notes component look nice, matching the designs (see comment below)
- [ ] css parts and custom properties for customizability

---

:moneybag: bitcoin bounty `50k satoshis`
:money_with_wings: falls in value by `5k satoshis` each day after 2021-11-15

**Comment by chase-moskal** [comment]
![Screenshot 2021-11-14 112049](https://user-images.githubusercontent.com/7145590/141695332-a975dcce-fd58-4301-9158-b534e72482b3.png)

**Comment by Dexterl00** [comment]
Commenting for assignment

**Comment by Tuasegun** [comment]
Is this issue still available @chase-moskal

**Comment by LewBlu** [comment]
Could I be assigned to this please?

**Comment by chase-moskal** [comment]
@LewBlu assigned :muscle:

**Comment by chase-moskal** [comment]
:tada: merged!
